name=MLX90614
slug=mlx90614
id=mlx90614
version=0.3.0
description=MLX90614 contactless I2C temperature sensor (object and ambient) with temperature listeners
repo=https://github.com/xewe-labs/xewe-os-modules/tree/main/modules/mlx90614
folder=Mlx90614
include=src/Mlx90614/Mlx90614.h
declare=Mlx90614 mlx90614(os);
depends_modules=
depends_libraries=ArduinoJson
requires_core=>=2.1.0,<3.0.0
