name=Scheduler
slug=scheduler
id=schedule
version=0.3.0
description=Runs stored commands on a weekly schedule
repo=https://github.com/xewe-labs/xewe-os-modules/tree/main/modules/scheduler
folder=Scheduler
include=src/Scheduler/Scheduler.h
declare=Scheduler scheduler(os, time_module);
depends_modules=time
depends_libraries=
requires_core=>=2.1.0,<3.0.0
