#!/usr/bin/env python3
"""Validate every module of this repo (CONTRACT.md section 5).

A thin wrapper: the module.properties rules come from xewe-os-tools (`xewe.modules.validate`);
this file adds only the repo-policy rules. Run it with a Python that has xewe-os-tools
installed, which is a harness venv:

    <harness>/build/.venv/bin/python tools/validate.py [--harness DIR]
    <harness>/build/.venv/bin/python tools/validate.py --write-index

Output: one `error|warning: <where>: <message>` line per finding, then
`N modules, E errors, W warnings`. Exit 0 no errors, 1 errors, 2 usage error, 3 tools missing.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
import tomllib
from pathlib import Path

EXIT_OK, EXIT_FAIL, EXIT_USAGE, EXIT_NOT_SETUP = 0, 1, 2, 3

REPO = Path(__file__).resolve().parents[1]
INDEX = "MODULES.md"
CATALOGUE = "libraries.toml"
REPO_URL = "https://github.com/xewe-labs/xewe-os-modules/tree/main/modules/{slug}"
LIBRARY_RE = re.compile(r"^[A-Za-z0-9_.\- ]+$")
FORBIDDEN_LIBRARIES = {"XeWeCore", "XeWeOS"}
# old API and the arduino-esp32 `cli()` macro; checked in every file of src/<folder>/
FORBIDDEN_SOURCE = (
    (re.compile(r"\bcli\s*\("), "'cli(' (arduino-esp32 defines cli() as a macro; use os.cli.execute)"),
    (re.compile(r"<XeWeOS\.h>"), "'<XeWeOS.h>' (include <XeWeCore.h>)"),
    (re.compile(r"xewe::os::"), "'xewe::os::' (old namespace; use xewe::)"),
    (re.compile(r"ModuleController"), "'ModuleController' (old API; take xewe::Os& host)"),
    (re.compile(r"\bcontroller\b"), "'controller' (old API; use the member os)"),
    (re.compile(r"xewe_cli"), "'xewe_cli' (old API; use os.cli)"),
    (re.compile(r"this->os\b"), "'this->os' (use os)"),
    (re.compile(r"std::span"), "'std::span' (use xewe::span)"),
)
INDEX_HEADER = (
    "<!-- Generated by `tools/validate.py --write-index`; do not edit. -->\n"
    "# Modules\n"
    "\n"
    "| Slug | Name | Id | Version | Description | Depends on | Requires core |\n"
    "|---|---|---|---|---|---|---|\n"
)


class Problem:
    """Same shape and `str()` as xewe.modules.Problem."""

    def __init__(self, where: str, message: str, error: bool = True) -> None:
        self.where, self.message, self.error = where, message, error

    def __str__(self) -> str:
        return f"{'error' if self.error else 'warning'}: {self.where}: {self.message}"


def render_index(registry) -> str:
    rows = []
    for m in registry.all:
        p = m.props
        deps = ", ".join(m.deps) or "-"
        cells = [f"[`{m.slug}`](modules/{m.dir.name})", p.get("name", ""), f"`{p.get('id', '')}`",
                 p.get("version", ""), p.get("description", ""), deps, f"`{p.get('requires_core', '')}`"]
        rows.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |\n")
    return INDEX_HEADER + "".join(rows)


def _string_literal(text: str, value: str) -> bool:
    return f'"{value}"' in text


def check_tests(path: Path, err) -> None:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except SyntaxError as exc:
        err(f"tests: {path.name} does not parse: {exc.msg} (line {exc.lineno})")
        return
    names = {n.name for n in tree.body if isinstance(n, ast.FunctionDef) and n.name.startswith("test_")}
    for required in ("test_compiles", "test_status"):
        if required not in names:
            err(f"tests: {required} missing in {path.name}")
    if not names - {"test_compiles", "test_status"}:
        err(f"tests: {path.name} needs at least one behaviour test besides test_compiles and test_status")


def read_catalogue() -> set[str]:
    """Library names pinned in libraries.toml (empty when the file is missing)."""
    path = REPO / CATALOGUE
    return set(tomllib.loads(path.read_text(encoding="utf-8"))) if path.is_file() else set()


def check_module(m, libraries: set[str] | None, catalogue: frozenset[str] | set[str] = frozenset()) -> list[Problem]:
    problems: list[Problem] = []
    where = m.slug or m.dir.name

    def err(msg: str, error: bool = True) -> None:
        problems.append(Problem(where, msg, error))

    p = m.props
    folder = p.get("folder", "")
    src = m.dir / "src" / folder
    header, cpp = src / f"{folder}.h", src / f"{folder}.cpp"

    # files
    for f in (header, cpp, m.dir / "README.md", m.dir / "tests" / f"test_{m.slug}.py"):
        if not f.is_file():
            err(f"files: {f.relative_to(m.dir)} missing")
    if p.get("include", "") != f"src/{folder}/{folder}.h":
        err(f"files: include '{p.get('include', '')}' must be src/{folder}/{folder}.h")
    for name in ("conftest.py", "__init__.py"):
        if (m.dir / "tests" / name).exists():
            err(f"files: tests/{name} not allowed (the plugin provides the fixtures)")

    # class, declare-os
    decl = m.declared()
    if decl is not None:
        dtype, _var, args = decl
        if dtype != folder:
            err(f"class: declare type '{dtype}' must equal folder '{folder}'")
        if not args or args[0] != "os":
            err(f"declare-os: first declare argument must be 'os', got '{args[0] if args else ''}'")

    # name, id-source
    cpp_text = cpp.read_text(encoding="utf-8") if cpp.is_file() else ""
    if cpp_text:
        if not _string_literal(cpp_text, p.get("name", "")):
            err(f"name: '\"{p.get('name', '')}\"' not found in {cpp.name} (must equal the C++ name argument)")
        if not _string_literal(cpp_text, p.get("id", "")):
            err(f"id-source: '\"{p.get('id', '')}\"' not found in {cpp.name}")

    # tests
    test_file = m.dir / "tests" / f"test_{m.slug}.py"
    if test_file.is_file():
        check_tests(test_file, err)

    # repo
    want = REPO_URL.format(slug=m.slug)
    if p.get("repo", "") != want:
        err(f"repo '{p.get('repo', '')}' must be {want}")

    # depends_libraries
    for lib in (x.strip() for x in p.get("depends_libraries", "").split(",")):
        if not lib:
            continue
        if not LIBRARY_RE.match(lib):
            err(f"depends_libraries: '{lib}' must match {LIBRARY_RE.pattern}")
        elif lib in FORBIDDEN_LIBRARIES:
            err(f"depends_libraries: '{lib}' must not be listed (XeWeCore comes from the harness)")
        elif libraries is not None and lib not in libraries and lib not in catalogue:
            err(f"depends_libraries: '{lib}' is neither in {CATALOGUE} nor in the harness xewe.lock [libraries]")
        elif lib not in catalogue:
            err(f"depends_libraries: '{lib}' is not in {CATALOGUE} (xewe setup will not install it)", error=False)

    # source
    if src.is_dir():
        for f in sorted(x for x in src.rglob("*") if x.is_file()):
            text = f.read_text(encoding="utf-8", errors="replace")
            for n, line in enumerate(text.splitlines(), 1):
                for rx, what in FORBIDDEN_SOURCE:
                    if rx.search(line):
                        err(f"source: {f.relative_to(m.dir)}:{n}: {what}")
        if header.is_file() and "#include <XeWeCore.h>" not in header.read_text(encoding="utf-8"):
            err(f"source: {header.name} must contain '#include <XeWeCore.h>'")

    # stray (inside the module)
    for f in sorted(m.dir.rglob("*.ino")):
        err(f"stray: {f.relative_to(m.dir)} (validation sketches are replaced by tests)")
    for name in ("scripts", "LICENSE.txt"):
        if (m.dir / name).exists():
            err(f"stray: {name} (one LICENSE.txt for the repo; no per-module scripts)")
    return problems


def check_repo(registry) -> list[Problem]:
    problems: list[Problem] = []
    modules_dir = REPO / "modules"
    allowed = {m.dir / "module.properties" for m in registry.all if m.dir.parent == modules_dir}
    for f in sorted(REPO.rglob("module.properties")):
        if f not in allowed and ".git" not in f.parts:
            problems.append(Problem("repo", f"stray: {f.relative_to(REPO)} (only modules/<slug>/module.properties)"))
    for f in sorted(REPO.rglob("*.ino")):
        if ".git" not in f.parts and modules_dir not in f.parents:
            problems.append(Problem("repo", f"stray: {f.relative_to(REPO)}"))
    for base in (REPO, modules_dir):
        for d in sorted(base.glob("xewe-os-module-*")):
            problems.append(Problem("repo", f"stray: {d.relative_to(REPO)}/ (old layout; use modules/<slug>/)"))
    return problems


def read_harness(path: Path) -> tuple[str | None, set[str]]:
    lock = path / "xewe.lock"
    if not lock.is_file():
        raise SystemExit(f"usage: --harness {path}: no xewe.lock there")
    data = tomllib.loads(lock.read_text(encoding="utf-8"))
    return data.get("core", {}).get("ref"), set(data.get("libraries", {}))


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Validate the modules of this repo (CONTRACT.md section 5).")
    ap.add_argument("--harness", type=Path, metavar="DIR",
                    help="xewe-os harness: its xewe.lock gives [core] ref and [libraries]")
    ap.add_argument("--write-index", action="store_true", help=f"rewrite {INDEX} and exit")
    args = ap.parse_args(argv)

    try:
        from xewe import modules as xm
    except ImportError:
        print("xewe-os-tools not importable; run with <harness>/build/.venv/bin/python", file=sys.stderr)
        return EXIT_NOT_SETUP

    core_ref, libraries = None, None
    if args.harness is not None:
        if not args.harness.is_dir():
            print(f"usage: --harness {args.harness}: not a directory", file=sys.stderr)
            return EXIT_USAGE
        try:
            core_ref, libs = read_harness(args.harness)
        except (SystemExit, tomllib.TOMLDecodeError) as exc:
            print(str(exc), file=sys.stderr)
            return EXIT_USAGE
        libraries = libs

    registry = xm.Registry.load(REPO)
    if args.write_index:
        (REPO / INDEX).write_text(render_index(registry), encoding="utf-8")
        print(f"wrote {INDEX} ({len(registry.all)} modules)")
        return EXIT_OK

    try:
        catalogue = read_catalogue()
    except tomllib.TOMLDecodeError as exc:
        print(f"{CATALOGUE}: invalid TOML: {exc}", file=sys.stderr)
        return EXIT_USAGE
    problems = list(xm.validate(registry, core_ref))
    for m in registry.all:
        if m.dir.parent == REPO / "modules":  # anything else is reported as stray by check_repo
            problems.extend(check_module(m, libraries, catalogue))
    problems.extend(check_repo(registry))
    index = REPO / INDEX
    if not index.is_file() or index.read_text(encoding="utf-8") != render_index(registry):
        problems.append(Problem("repo", f"index: {INDEX} is out of date; run tools/validate.py --write-index"))

    for problem in problems:
        print(str(problem))
    errors = sum(1 for x in problems if x.error)
    print(f"{len(registry.all)} modules, {errors} errors, {len(problems) - errors} warnings")
    return EXIT_FAIL if errors else EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
