name=Buttons
slug=buttons
id=buttons
version=0.2.0
description=Binds commands to physical buttons with software debouncing
repo=https://github.com/xewe-labs/xewe-os-modules/tree/main/modules/buttons
folder=Buttons
include=src/Buttons/Buttons.h
declare=Buttons buttons(os);
depends_modules=
depends_libraries=
requires_core=>=2.0.0,<3.0.0
